=== ty180703/suade-challenge/SuadeTask/FSA029-Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    ****************************************************************************************************
    *                                                                 
    *    Schema for: Data Item FSA029-BalanceSheet                    
    *                                                                 
    *    Version:   4
    *    Date:      28 June 2022                                 
    *                                                                 
    *    History:   Version 4 changes the CommonTypes-Schema to Version 14 and removes the SDS003-Schema
    *
    *               Version 3 adds "GroupInfo" element to allow group reporting 
    
    *               Version 2 changes the CurrentLiabilities element to minOccurs="1"
    *                   
    *               Version 1 follows publication of legal instruments 2007/10 and 2007/45            
    *                                                                 
    ****************************************************************************************************
-->

<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified" 
    
    targetNamespace="urn:fsa-gov-uk:MER:FSA029:4"
    xmlns=          "urn:fsa-gov-uk:MER:FSA029:4" 
    xmlns:mer-meta= "urn:fsa-gov-uk:MER:Meta-Data:2" 
    
    version="4" 
    id="MER-FSA029">
    
    <xs:annotation>
        <xs:documentation>
            <mer-meta:DataItemReference>FSA029</mer-meta:DataItemReference>
            <mer-meta:DataItemName>Balance Sheet</mer-meta:DataItemName>
        </xs:documentation>
    </xs:annotation>
    
    <xs:include schemaLocation="../../CommonTypes/v14/CommonTypes-Schema.xsd"/>

    <xs:element name="FSA029-BalanceSheet">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="GroupInfo" type="GroupFRNStructure" minOccurs="0"/>
                
                <xs:element name="FixedAssets"            minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="IntangibleAssets" type="MonetaryType" minOccurs="0"/>
                            <xs:element name="TangibleAssets"   type="MonetaryType" minOccurs="0"/>
                            <xs:element name="Investments"      type="MonetaryType" minOccurs="0"/>
                            <xs:element name="TotalFixedAssets" type="MonetaryType" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="CurrentAssets"          minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="StocksInvestments" type="MonetaryType" minOccurs="0"/>
                            <xs:element name="TradeDebtors"      minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Within90" type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="After90"  type="MonetaryType" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>    
                            <xs:element name="NonTradeDebtors"  type="MonetaryType" minOccurs="0"/>
                            <xs:element name="SundryDebtors"    type="MonetaryType" minOccurs="0"/>
                            <xs:element name="LoansOtherAssets" type="MonetaryType" minOccurs="0"/>
                            <xs:element name="Cash"             minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Segregated"    type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="NonSegregated" type="MonetaryType" minOccurs="0"/>                                       
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="TotalCurrentAssets" type="MonetaryType" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="CurrentLiabilities"     minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Creditors"        type="MonetaryType" minOccurs="0"/>
                            <xs:element name="SundryCreditors"  type="MonetaryType" minOccurs="0"/>
                            <xs:element name="Accruals"         type="MonetaryType" minOccurs="0"/>
                            <xs:element name="LoansWithin1year" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="BankLoansSegregated"    type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="BankLoansNonSegregated" type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="ShortTermSubLoan"       type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="LongTermSubLoan"        type="MonetaryType" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Total" type="MonetaryType" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="NetCurrentAssets"       type="MonetaryType" minOccurs="1"/>
                                
                <xs:element name="LongTermLiabilities"    minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Creditors"       type="MonetaryType" minOccurs="0"/>
                            <xs:element name="LoansAfter1year" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="BankLoansSegregated"    type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="BankLoansNonSegregated" type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="ShortTermSubLoan"       type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="LongTermSubLoan"        type="MonetaryType" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="TotalLongTermLiabilities" type="MonetaryType" minOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="TotalAssetsLiabilities" type="MonetaryType" minOccurs="1" />
                
                <xs:element name="Capital"                minOccurs="1">
                    <xs:complexType>
                        <xs:choice>
                            
                            <xs:element name="IncorporatedEntities" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="OrdinaryShares"                type="NonNegativeMonetaryType" minOccurs="0"/>
                                        <xs:element name="NonCumulativePreferenceShares" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Fixed"    type="NonNegativeMonetaryType" minOccurs="0"/>
                                                    <xs:element name="NonFixed" type="NonNegativeMonetaryType" minOccurs="0"/>                                                   
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="CumulativePreferenceShares" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Fixed"    type="NonNegativeMonetaryType" minOccurs="0"/>
                                                    <xs:element name="NonFixed" type="NonNegativeMonetaryType" minOccurs="0"/>
                                                    <xs:element name="Total"    type="NonNegativeMonetaryType" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="SharePremiumAccount"   type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="OtherReserves"         type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="RevaluationReserve"    type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="RetainedEarnings"      type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="ProfitLossCurrentYear" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="ExternallyVerified"       type="MonetaryType" minOccurs="0" />
                                                    <xs:element name="UnverifiedTradingBook"    type="MonetaryType" minOccurs="0" />
                                                    <xs:element name="UnverifiedNonTradingBook" type="MonetaryType" minOccurs="0" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="TotalCapital"    type="MonetaryType"             minOccurs="1"/>
                                        <xs:element name="OffBalanceSheet" type="OffBalanceSheetStructure" minOccurs="0"/>
                                     </xs:sequence>
                                </xs:complexType>
                            </xs:element>
             
                            <xs:element name="PartnershipsSoleTraders" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="CapitalAccount"            type="MonetaryType" minOccurs="1"/>
                                        <xs:element name="RetainedEarnings"          type="MonetaryType" minOccurs="0"/>
                                        <xs:element name="CurrentAccountCurrentYear" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="ExternallyVerified"       type="MonetaryType" minOccurs="0"/>
                                                    <xs:element name="UnverifiedTradingBook"    type="MonetaryType" minOccurs="0"/>
                                                    <xs:element name="UnverifiedNonTradingBook" type="MonetaryType" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="TotalCapital"    type="MonetaryType" minOccurs="1"/>
                                        <xs:element name="OffBalanceSheet" type="OffBalanceSheetStructure" minOccurs="0"/>
                                     </xs:sequence>
                                </xs:complexType> 
                            </xs:element>
                            
                            <xs:element name="LLPs" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="PartnersCashCapitalAccounts" type="MonetaryType" minOccurs="1"/>
                                        <xs:element name="PartnersCurrentAccounts"     type="MonetaryType" minOccurs="1"/>
                                        <xs:element name="TotalPartnersCapital"        type="MonetaryType" minOccurs="1"/>
                                        <xs:element name="OffBalanceSheet" type="OffBalanceSheetStructure" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                        </xs:choice>
                    </xs:complexType>
                </xs:element>             
            </xs:sequence> 
            <xs:attribute name="reportingBasis" type="ReportingBasisType" use="required"/>
            <xs:attributeGroup ref="CurrencyAndUnitsAttrGroup"/>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="OffBalanceSheetStructure">
        <xs:sequence>
            <xs:element name="Item" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ItemType" minOccurs="1">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Structured Products"/>
                                    <xs:enumeration value="OTCs"/>
                                    <xs:enumeration value="Derivatives"/>
                                    <xs:enumeration value="Operating Leases"/>
                                    <xs:enumeration value="Offshore Entities"/>
                                    <xs:enumeration value="Securitised Transactions"/>
                                    <xs:enumeration value="Other"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="Value"    type="MonetaryType" minOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
                
</xs:schema>

=== ty180703/suade-challenge/SuadeTask/FSA029-Sample-Valid.xml
<?xml version="1.0" encoding="UTF-8"?>

<FSA029-BalanceSheet
    xmlns:xsi=          "http://www.w3.org/2001/XMLSchema-instance"
    xmlns=              "urn:fsa-gov-uk:MER:FSA029:4"
    xsi:schemaLocation= "urn:fsa-gov-uk:MER:FSA029:4 http://www.fsa.gov.uk/MER/DRG/FSA029/v4/FSA029-Schema.xsd"
 	
	reportingBasis="Investment firm group"    
	currency= "GBP"
    	units=    "thousands">

    <GroupInfo>
        <OtherGroupFirms>
            <FirmReferenceNumber>123456</FirmReferenceNumber>
            <FirmReferenceNumber>234567</FirmReferenceNumber>
        </OtherGroupFirms>
    </GroupInfo>

    <FixedAssets>
        <IntangibleAssets>58530</IntangibleAssets>
        <TangibleAssets>24000</TangibleAssets>
        <Investments>8000</Investments>
        <TotalFixedAssets>90530</TotalFixedAssets>
    </FixedAssets>

    <CurrentAssets>
        <StocksInvestments>1000</StocksInvestments>
        <TradeDebtors>
            <Within90>200</Within90>
            <After90>450</After90>
        </TradeDebtors>
        <NonTradeDebtors>150</NonTradeDebtors>
        <SundryDebtors>50</SundryDebtors>
        <LoansOtherAssets>100</LoansOtherAssets>
        <Cash>
            <Segregated>250</Segregated>
            <NonSegregated>150</NonSegregated>
        </Cash>
        <TotalCurrentAssets>2350</TotalCurrentAssets>
    </CurrentAssets>

    <CurrentLiabilities>
        <Creditors>120</Creditors>
        <SundryCreditors>0</SundryCreditors>
        <Accruals>30</Accruals>
        <LoansWithin1year>
            <BankLoansSegregated>50</BankLoansSegregated>
            <BankLoansNonSegregated>25</BankLoansNonSegregated>
            <ShortTermSubLoan>25</ShortTermSubLoan>
            <LongTermSubLoan>0</LongTermSubLoan>
        </LoansWithin1year>
        <Total>250</Total>
    </CurrentLiabilities>
    <NetCurrentAssets>2100</NetCurrentAssets>
    <LongTermLiabilities>
        <Creditors>80</Creditors>
        <LoansAfter1year>
            <BankLoansSegregated>70</BankLoansSegregated>
            <BankLoansNonSegregated>50</BankLoansNonSegregated>
            <ShortTermSubLoan>0</ShortTermSubLoan>
            <LongTermSubLoan>0</LongTermSubLoan>
        </LoansAfter1year>
        <TotalLongTermLiabilities>200</TotalLongTermLiabilities>
    </LongTermLiabilities>

    <TotalAssetsLiabilities>92430</TotalAssetsLiabilities>

    <Capital>
        <IncorporatedEntities>
            <OrdinaryShares>10000</OrdinaryShares>
            <NonCumulativePreferenceShares>
                <Fixed>5000</Fixed>
                <NonFixed>0</NonFixed>
            </NonCumulativePreferenceShares>
            <CumulativePreferenceShares>
                <Fixed>5000</Fixed>
                <NonFixed>0</NonFixed>
                <Total>5000</Total>
            </CumulativePreferenceShares>
            <SharePremiumAccount>1000</SharePremiumAccount>
            <OtherReserves>800</OtherReserves>
            <RevaluationReserve>200</RevaluationReserve>
            <RetainedEarnings>7000</RetainedEarnings>
            <ProfitLossCurrentYear>
                <ExternallyVerified>62930</ExternallyVerified>
                <UnverifiedTradingBook>500</UnverifiedTradingBook>
                <UnverifiedNonTradingBook>0</UnverifiedNonTradingBook>
            </ProfitLossCurrentYear>
            <TotalCapital>92430</TotalCapital>
            <OffBalanceSheet>
                <Item>
                    <ItemType>OTCs</ItemType>
                    <Value>1000</Value>
                </Item>
                <Item>
                    <ItemType>Derivatives</ItemType>
                    <Value>2000</Value>
                </Item>
            </OffBalanceSheet>
        </IncorporatedEntities>
    </Capital>

 

</FSA029-BalanceSheet>
